# TODO List
# Feature branches: test
# Dev: test, build
# Main: tets, build to apk, anlyse, send email notification
# Make it so you ccant push to main or dev, only PR
# Make it so dev automatically gets merged into main every two weeks

name: CI
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
      - development
      
jobs:
  flutter_test:
    name: Flutter Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: 
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter test

  flutter_build:
    name: Flutter Build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development'
    needs: flutter_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: 
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter build apk
      - uses: actions/upload-artifact@v3
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk
      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "build/app/outputs/flutter-apk/app-release.apk"
          tags: true
          draft: true
  
  flutter_analyse:
    name: Flutter Analyse
    if: github.ref == 'refs/heads/main'
    needs: flutter_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: 
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze    
    
